### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by hharkat** [mahmoudnafifi/WB_color_augmenter#3]
Please I got the issue in matlab:
Index exceeds the number of array elements (0).

Error in WBAug (line 164)
                indices(i)}),...

Error in demo_WB_color_augmentation (line 75)
success = WBAug(training_set_dir, training_ext, output_dir, output_ext, ...
 
>> I believe that it is because my grougthruth images are logical type, how to fix this?

**Comment by mahmoudnafifi** [comment]
The error means that your ground truth filenames do not match the same filenames in the training directory. If you are sure it is not the case, so please check the `training_ext` and `ground_truth_ext`. Remember that even if you have a single file extension it should be represented as a cell (for example `ground_truth_ext = {'.png'};`). 

I hope that helps!

**Comment by hharkat** [comment]
Yes, I corrected the problem.
Effectivelly, it was that.
Thank you so much for making the code available and for your help.

**Comment by mahmoudnafifi** [comment]
Glad to hear you fixed it!
