### ISSUE TITLE
Can we use more than 10 ?

### ISSUE THREAD

**Issue by nedimmuzoglu** [mahmoudnafifi/WB_color_augmenter#4]
Hi Mr Mahmoud,
Can we increase the  number 10  in demo_batch.m, up to number of images in my directory?
It is about these codes..
if NumOfImgs > 10
    error('Cannot generate more than 10 images for each input image');
end

**Comment by mahmoudnafifi** [comment]
Hi @nedimmuzoglu, 
Thanks for raising this point. This is capped by the data we use (five white-balance settings and two different camera styles). So, for each image in your directory, you can generate up to 10 new versions with different "white-balance settings and camera styles". If you need more (per image), you may think of linearly interpolating between the generated images, but I am not sure if this blending would generate images with obvious differences or not.

**Comment by nedimmuzoglu** [comment]
I will use your  Efficient Contrast Enhancement Using Adaptive Gamma
Correction With Weighting Distribution method instead in my study first.
thank you for your interest
