### ISSUE TITLE
Can we set the output to be C/D/F/S/T?

### ISSUE THREAD

**Issue by agfianf** [mahmoudnafifi/WB_color_augmenter#5]
Hi Thanks for amazing works!

for Python Api: Can we set the output to be C/D/F/S/T rather than generate by num its self?

**Comment by mahmoudnafifi** [comment]
You can. Check [`self.wb_photo_finishing`](https://github.com/mahmoudnafifi/WB_color_augmenter/blob/59455266ea47ecfca3700b5677dad3a14b91fc3f/WBAugmenter_Python/WBAugmenter/WBEmulator.py#L42), where string in the list represents the white-balance setting and picture style; e.g., `_D_CS` is for white-balance: daylight and picture style: camera style. The function [`generateWbsRGB`](https://github.com/mahmoudnafifi/WB_color_augmenter/blob/59455266ea47ecfca3700b5677dad3a14b91fc3f/WBAugmenter_Python/WBAugmenter/WBEmulator.py#L87) returns `synthWBimages` (a list of the generated images in the same order specified in [`self.wb_photo_finishing`](https://github.com/mahmoudnafifi/WB_color_augmenter/blob/59455266ea47ecfca3700b5677dad3a14b91fc3f/WBAugmenter_Python/WBAugmenter/WBEmulator.py#L42)). So, you can change the code accordingly, or simply select the target white-balance settings from the returned `synthWBimages` list.

**Comment by agfianf** [comment]
i see, it works. Thanks
