### ISSUE TITLE
Do images with new WBs need to be normalised before being fed into a model for image classification?

### ISSUE THREAD

**Issue by a2108870** [mahmoudnafifi/WB_color_augmenter#7]
In the paper you mention that you tested images from the imagenet with the new WB settings, do these images need to be normalised before being fed into the vgg or resnet models?

**Comment by mahmoudnafifi** [comment]
What do you mean by normalized? Any training preprocessing should be applied in testing too, that includes mean subtraction and division by std.

**Comment by a2108870** [comment]
Thank you very much！

**Comment by mahmoudnafifi** [comment]
You are welcome!
